/////////////////////USUARIOS REGISTRADOS/////////////////////

//Ejemplo register
POST http://localhost:4000/api/auth/register HTTP/1.1
Content-Type: application/json
//api_key: Api-publica-123

{
    "name": "POST1",
    "email": "POST1@post.com",
    "password": "POST1",
    "age": 20,
    "ciudad": "Madrid",
    "intereses": ["deportes", "cine"],
    "recibirOfertas": false
}

###
//Ejemplo login
POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json
//api_key: Api-publica-123

{
    "email": "ADMIN@admin.com",
    "password": "ADMIN"  
}

###
//Ejemplo login
POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json
//api_key: Api-publica-123

{
    "email": "POST3@post.com",
    "password": "POST3"  
}

###
//Ejemplo updateUser
PUT http://localhost:4000/api/users/POST3@post.com HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFmZmM4Yjc4NDdkYjllZWJhYjhlMjEiLCJlbWFpbCI6IlBPU1QzQHBvc3QuY29tIiwiaWF0IjoxNzEzOTgyOTczLCJleHAiOjE3MTc0Mzg5NzN9.GsUYuq8Eh6wj-YfOMvjTY7fzEBfkNEnEG2JmTtpObeI

{
    "name": "POST3_modificado",
    "ciudad": "Barcelona",
    "recibirOfertas": false,
    "intereses": ["deportes", "cine", "teatro"]
}

###
//Ejemplo getUsers de la misma ciudad y reciben ofertas (solo para comercios)
GET http://localhost:4000/api/users/interested/POSTCOMERCIO2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjIwMDcxYTRhZTBmM2I2MjM4NDJmMzEiLCJlbWFpbCI6IlBPU1RDT01FUkNJTzJAcG9zdC5jb20iLCJjaWYiOiJQT1NUQ09NRVJDSU8yIiwiaWF0IjoxNzE0MTQ3MjExLCJleHAiOjE3MTc2MDMyMTF9.zXWSfOsLzHswqyziiH-a0AZWBOsj6J3PnUTQmbzAQnM

###
//Ejemplo getUsers
GET http://localhost:4000/api/users HTTP/1.1

###
//Ejemplo getUser
GET http://localhost:4000/api/users/POST3@post.com HTTP/1.1

###
//Ejemplo deleteUser
DELETE http://localhost:4000/api/users/POST1@post.com HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWIzOTVkNDQxNjBlNjQ4Y2MwMmEiLCJlbWFpbCI6IlBPU1QxQHBvc3QuY29tIiwiaWF0IjoxNzEzMjg1OTQ1LCJleHAiOjE3MTUwMTM5NDV9.cbTQ4kM1-Hx6B9RxTooXqXlENmqTVEOtkPvHpRckJO0

###
//Ejemplo publicar reseñas
PUT http://localhost:4000/api/users/reviews/POSTCOMERCIO2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWIzOTVkNDQxNjBlNjQ4Y2MwMmEiLCJlbWFpbCI6IlBPU1QxQHBvc3QuY29tIiwiaWF0IjoxNzEzNDM2MTAyLCJleHAiOjE3MTY4OTIxMDJ9.yw6ia3jVMC4OKyqfoleVdj5vwYov39-RH61xxXEFSQM

{
    "cif": "POSTCOMERCIO2",
    "webpage": {
        "scoring": 9,
        "reseñas": "test"
    }
}

/////////////////////COMERCIOS/////////////////////


###
//Ejemplo crear comercio (SOLO PARA ADMINS)
POST http://localhost:4000/api/auth/registerComerce HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWIxYzVkNDQxNjBlNjQ4Y2MwMjgiLCJlbWFpbCI6IkFETUlOQGFkbWluLmNvbSIsImlhdCI6MTcxMzk4NDcwMSwiZXhwIjoxNzE3NDQwNzAxfQ.nYMS_IbMRdtPT1VKt-zlHOyO6hXQLGpi9wcA1qBAXg4

{
    "name": "POSTCOMERCIO4",
    "cif": "POSTCOMERCIO4",
    "direccion": "Calle POSTCOMERCIO4, 4",
    "email": "POSTCOMERCIO4@post.com",
    "password": "POSTCOMERCIO4",
    "telefono": "123456789"
}

###
//Ejemplo crear comercio (SOLO PARA ADMINS)
POST http://localhost:4000/api/auth/registerComerce HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWIxYzVkNDQxNjBlNjQ4Y2MwMjgiLCJlbWFpbCI6IkFETUlOQGFkbWluLmNvbSIsImlhdCI6MTcxMzI4ODc5OSwiZXhwIjoxNzE1MDE2Nzk5fQ.2Kz_rlcPgbvS_xSYEXs-VbdFRVCXXCWVlKwoD2Sa-ac

{
    "name": "COMERCIOTEST",
    "cif": "COMERCIOTEST",
    "direccion": "Calle COMERCIOTEST, 3",
    "email": "COMERCIOTEST@post.com",
    "password": "COMERCIOTEST",
    "telefono": "45346735"
}

###
//Ejemplo login comercio
POST http://localhost:4000/api/auth/loginComerce HTTP/1.1
Content-Type: application/json
//api_key: Api-publica-123

{
    "email": "POSTCOMERCIO2@post.com",
    "password": "POSTCOMERCIO2"  
}

###
//Ejemplo getComerces
GET http://localhost:4000/api/comerce HTTP/1.1

###
//Ejemplo getComerce
GET http://localhost:4000/api/comerce/merchant/POSTCOMERCIO2 HTTP/1.1

###
//Ejemplo updateComerce (SOLO PARA ADMINS)
PUT http://localhost:4000/api/comerce/POSTCOMERCIO2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWIxYzVkNDQxNjBlNjQ4Y2MwMjgiLCJlbWFpbCI6IkFETUlOQGFkbWluLmNvbSIsImlhdCI6MTcxMzM3NDY0MywiZXhwIjoxNzE2ODMwNjQzfQ.fRgpTQ0ESZsyA9mPx2ILbQyuEsp18gFGBbfOAT94pys

{
    "name": "POSTCOMERCIO2_modificado",
    "direccion": "Calle POSTCOMERCIO2_modificado, 1",
    "email": "POSTCOMERCIO2_modificado@post.com",
    "password": "POSTCOMERCIO2_modificado",
    "telefono": "918273645"
}

###
//Ejemplo deleteComerce
DELETE http://localhost:4000/api/comerce/POSTCOMERCIO4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWIxYzVkNDQxNjBlNjQ4Y2MwMjgiLCJlbWFpbCI6IkFETUlOQGFkbWluLmNvbSIsImlhdCI6MTcxNDA0ODUwOCwiZXhwIjoxNzE3NTA0NTA4fQ.oIXS_VZKmLOyNnsSkGJQXZBCR_62MMrmVEo431Z-G_E


//////////////////////////////PAGINAS WEB/////////////////////////


###
//Ejemplo createWebPage
POST http://localhost:4000/api/comerce/webpages HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJiNmZiNDk2M2NkZmFhODFjMWNlY2IiLCJlbWFpbCI6IkNPTUVSQ0lPVEVTVEBwb3N0LmNvbSIsImNpZiI6IkNPTUVSQ0lPVEVTVCIsImlhdCI6MTcxNDEyMzQyMywiZXhwIjoxNzE3NTc5NDIzfQ.o0agJIMUE1F6f-3rCSjcskP4Xm5_lQ82CvxmAWpjDRc

{
    "cif": "COMERCIOTEST",
    "webpage": {
        "ciudad": "TEST",
        "actividad": "TEST",
        "titulo": "TEST",
        "resumen": "TEST",
        "textos": "TEST",
        "fotos": "TEST.jpg"
    }
}

###
//Ejemplo getWebPage
GET http://localhost:4000/api/comerce/webpages/POSTCOMERCIO2 HTTP/1.1

###
//Ejemplo getWebPages
GET http://localhost:4000/api/comerce/webpages HTTP/1.1

###
//Ejemplo getWebPages con filtros
//?order=true
//?actividad=comida
//?ciudad=barcelona
GET http://localhost:4000/api/comerce/webpages?order=true&actividad=ropa&ciudad=madrid HTTP/1.1

###
//Ejemplo updateWebPage
PUT http://localhost:4000/api/comerce/webpages/POSTCOMERCIO2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjIwMDcxYTRhZTBmM2I2MjM4NDJmMzEiLCJlbWFpbCI6IlBPU1RDT01FUkNJTzJAcG9zdC5jb20iLCJjaWYiOiJQT1NUQ09NRVJDSU8yIiwiaWF0IjoxNzEzMzc1MDA3LCJleHAiOjE3MTY4MzEwMDd9.HMjhV1fQK-K7DHVfCgYja47ThcNc9pnJOle-3HGkHHc

{
    "webpage": {
        "ciudad": "Barcelona",
        "actividad": "Tienda de comida",
        "titulo": "Mi página web",
        "resumen": "Bienvenidos a mi página web",
        "textos": "HOLA",
        "fotos": "imagen4.jpg"
    }
}

###
//Ejemplo deleteWebPage
DELETE http://localhost:4000/api/comerce/webpages/COMERCIOTEST HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJiNmZiNDk2M2NkZmFhODFjMWNlY2IiLCJlbWFpbCI6IkNPTUVSQ0lPVEVTVEBwb3N0LmNvbSIsImNpZiI6IkNPTUVSQ0lPVEVTVCIsImlhdCI6MTcxNDEyMzQyMywiZXhwIjoxNzE3NTc5NDIzfQ.o0agJIMUE1F6f-3rCSjcskP4Xm5_lQ82CvxmAWpjDRc

###
//Ejemplo subir foto
PUT http://localhost:4000/api/comerce/webpages/upload/POSTCOMERCIO2 HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjIwMDcxYTRhZTBmM2I2MjM4NDJmMzEiLCJlbWFpbCI6IlBPU1RDT01FUkNJTzJAcG9zdC5jb20iLCJjaWYiOiJQT1NUQ09NRVJDSU8yIiwiaWF0IjoxNzE0MTQ1MTM1LCJleHAiOjE3MTc2MDExMzV9.MR81sbUYALuzLk3RIWQz0NYeae-QDV4QkLtIKCMA2TA

--Boundry
Content-Disposition: form-data; name="image"; filename="img.png"
Content-Type: image/png

< ./img.png
--Boundry--


###
//Prueba SLACK
// Ejemplo generar error 404
GET http://localhost:4000/api/error HTTP/1.1