/////////////////////USUARIOS REGISTRADOS/////////////////////

//Ejemplo register
POST http://localhost:4000/api/auth/register HTTP/1.1
Content-Type: application/json
//api_key: Api-publica-123

{
    "name": "POST1",
    "email": "POST1@post.com",
    "password": "POST1",
    "age": 20,
    "ciudad": "Madrid",
    "intereses": ["deportes", "cine"],
    "recibirOfertas": false
}

###
//Ejemplo login
POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json
//api_key: Api-publica-123

{
    "email": "ADMIN@admin.com",
    "password": "ADMIN"  
}

###
//Ejemplo login
POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json
//api_key: Api-publica-123

{
    "email": "POST3@post.com",
    "password": "POST3"  
}

###
//Ejemplo updateUser
PUT http://localhost:4000/api/users/POST3@post.com HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFmZmM4Yjc4NDdkYjllZWJhYjhlMjEiLCJlbWFpbCI6IlBPU1QzQHBvc3QuY29tIiwiaWF0IjoxNzEzOTgyOTczLCJleHAiOjE3MTc0Mzg5NzN9.GsUYuq8Eh6wj-YfOMvjTY7fzEBfkNEnEG2JmTtpObeI

{
    "name": "POST3_modificado",
    "ciudad": "Barcelona",
    "recibirOfertas": false,
    "intereses": ["deportes", "cine", "teatro"]
}

###
//Ejemplo getUsers de la misma ciudad y reciben ofertas (solo para comercios)
GET http://localhost:4000/api/users/interested/POSTCOMERCIO2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjIwMDcxYTRhZTBmM2I2MjM4NDJmMzEiLCJlbWFpbCI6IlBPU1RDT01FUkNJTzJAcG9zdC5jb20iLCJjaWYiOiJQT1NUQ09NRVJDSU8yIiwiaWF0IjoxNzEzNjEyMDc1LCJleHAiOjE3MTcwNjgwNzV9.UqLsnXk14FnoFuLOP3_7sPmv7KQUwfjS-eG3n0oqy5A

###
//Ejemplo getUsers
GET http://localhost:4000/api/users HTTP/1.1

###
//Ejemplo getUser
GET http://localhost:4000/api/users/POST3@post.com HTTP/1.1

###
//Ejemplo deleteUser
DELETE http://localhost:4000/api/users/POST1@post.com HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWIzOTVkNDQxNjBlNjQ4Y2MwMmEiLCJlbWFpbCI6IlBPU1QxQHBvc3QuY29tIiwiaWF0IjoxNzEzMjg1OTQ1LCJleHAiOjE3MTUwMTM5NDV9.cbTQ4kM1-Hx6B9RxTooXqXlENmqTVEOtkPvHpRckJO0

###
//Ejemplo publicar reseñas
PUT http://localhost:4000/api/users/reviews/POSTCOMERCIO2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWIzOTVkNDQxNjBlNjQ4Y2MwMmEiLCJlbWFpbCI6IlBPU1QxQHBvc3QuY29tIiwiaWF0IjoxNzEzNDM2MTAyLCJleHAiOjE3MTY4OTIxMDJ9.yw6ia3jVMC4OKyqfoleVdj5vwYov39-RH61xxXEFSQM

{
    "cif": "POSTCOMERCIO2",
    "webpage": {
        "scoring": 9,
        "reseñas": "test"
    }
}

/////////////////////COMERCIOS/////////////////////


###
//Ejemplo crear comercio (SOLO PARA ADMINS)
POST http://localhost:4000/api/auth/registerComerce HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWIxYzVkNDQxNjBlNjQ4Y2MwMjgiLCJlbWFpbCI6IkFETUlOQGFkbWluLmNvbSIsImlhdCI6MTcxMzk4NDcwMSwiZXhwIjoxNzE3NDQwNzAxfQ.nYMS_IbMRdtPT1VKt-zlHOyO6hXQLGpi9wcA1qBAXg4

{
    "name": "POSTCOMERCIO4",
    "cif": "POSTCOMERCIO4",
    "direccion": "Calle POSTCOMERCIO4, 4",
    "email": "POSTCOMERCIO4@post.com",
    "password": "POSTCOMERCIO4",
    "telefono": "123456789"
}

###
//Ejemplo crear comercio (SOLO PARA ADMINS)
POST http://localhost:4000/api/auth/registerComerce HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWIxYzVkNDQxNjBlNjQ4Y2MwMjgiLCJlbWFpbCI6IkFETUlOQGFkbWluLmNvbSIsImlhdCI6MTcxMzI4ODc5OSwiZXhwIjoxNzE1MDE2Nzk5fQ.2Kz_rlcPgbvS_xSYEXs-VbdFRVCXXCWVlKwoD2Sa-ac

{
    "name": "POSTCOMERCIO3",
    "cif": "POSTCOMERCIO3",
    "direccion": "Calle POSTCOMERCIO3, 3",
    "email": "POSTCOMERCIO3@post.com",
    "password": "POSTCOMERCIO3",
    "telefono": "45346735"
}

###
//Ejemplo login comercio
POST http://localhost:4000/api/auth/loginComerce HTTP/1.1
Content-Type: application/json
//api_key: Api-publica-123

{
    "email": "POSTCOMERCIO2@post.com",
    "password": "POSTCOMERCIO2"  
}

###
//Ejemplo getComerces
GET http://localhost:4000/api/comerce HTTP/1.1

###
//Ejemplo getComerce
GET http://localhost:4000/api/comerce/merchant/POSTCOMERCIO2 HTTP/1.1

###
//Ejemplo updateComerce (SOLO PARA ADMINS)
PUT http://localhost:4000/api/comerce/POSTCOMERCIO2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWIxYzVkNDQxNjBlNjQ4Y2MwMjgiLCJlbWFpbCI6IkFETUlOQGFkbWluLmNvbSIsImlhdCI6MTcxMzM3NDY0MywiZXhwIjoxNzE2ODMwNjQzfQ.fRgpTQ0ESZsyA9mPx2ILbQyuEsp18gFGBbfOAT94pys

{
    "name": "POSTCOMERCIO2_modificado",
    "direccion": "Calle POSTCOMERCIO2_modificado, 1",
    "email": "POSTCOMERCIO2_modificado@post.com",
    "password": "POSTCOMERCIO2_modificado",
    "telefono": "918273645"
}

###
//Ejemplo deleteComerce
DELETE http://localhost:4000/api/comerce/POSTCOMERCIO4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWIxYzVkNDQxNjBlNjQ4Y2MwMjgiLCJlbWFpbCI6IkFETUlOQGFkbWluLmNvbSIsImlhdCI6MTcxMzk4NDg3OCwiZXhwIjoxNzE3NDQwODc4fQ.0uXthrbk2x6VmExYFbNJYNwEmf953bjcxxlBS3UnNbY


//////////////////////////////PAGINAS WEB/////////////////////////


###
//Ejemplo createWebPage
POST http://localhost:4000/api/comerce/webpages HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjIzOGZhM2M2NzNkZThjNTQ2ZWVjMGQiLCJlbWFpbCI6IlBPU1RDT01FUkNJTzFAcG9zdC5jb20iLCJjaWYiOiJQT1NUQ09NRVJDSU8xIiwiaWF0IjoxNzEzNjA3MjQ3LCJleHAiOjE3MTcwNjMyNDd9.ZMQtngn9F_MvkgTqLOwoX3jQw0XtoQudS2bBuC3Yr2o

{
    "cif": "POSTCOMERCIO1",
    "webpage": {
        "ciudad": "Madrid",
        "actividad": "Tienda de ropa",
        "titulo": "Mi página web",
        "resumen": "Bienvenidos a mi página web",
        "textos": "texto1",
        "fotos": "imagen1.jpg"
    }
}

###
//Ejemplo getWebPage
GET http://localhost:4000/api/comerce/webpages/POSTCOMERCIO2 HTTP/1.1

###
//Ejemplo getWebPages
GET http://localhost:4000/api/comerce/webpages HTTP/1.1

###
//Ejemplo getWebPages con filtros
//?order=true
//?actividad=comida
//?ciudad=barcelona
GET http://localhost:4000/api/comerce/webpages?order=true&actividad=ropa&ciudad=madrid HTTP/1.1

###
//Ejemplo updateWebPage
PUT http://localhost:4000/api/comerce/webpages/POSTCOMERCIO2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjIwMDcxYTRhZTBmM2I2MjM4NDJmMzEiLCJlbWFpbCI6IlBPU1RDT01FUkNJTzJAcG9zdC5jb20iLCJjaWYiOiJQT1NUQ09NRVJDSU8yIiwiaWF0IjoxNzEzMzc1MDA3LCJleHAiOjE3MTY4MzEwMDd9.HMjhV1fQK-K7DHVfCgYja47ThcNc9pnJOle-3HGkHHc

{
    "webpage": {
        "ciudad": "Barcelona",
        "actividad": "Tienda de comida",
        "titulo": "Mi página web",
        "resumen": "Bienvenidos a mi página web",
        "textos": "HOLA",
        "fotos": "imagen4.jpg"
    }
}

###
//Ejemplo deleteWebPage
DELETE http://localhost:4000/api/comerce/webpages/POSTCOMERCIO2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjIwMDcxYTRhZTBmM2I2MjM4NDJmMzEiLCJlbWFpbCI6IlBPU1RDT01FUkNJTzJAcG9zdC5jb20iLCJjaWYiOiJQT1NUQ09NRVJDSU8yIiwiaWF0IjoxNzEzMzc3MTk0LCJleHAiOjE3MTY4MzMxOTR9.OkaoRNPYvSWEcwY0Y627hpgKoTYXEVMzkv2MFdmEM2w

###
//Prueba SLACK
// Ejemplo generar error 404
GET http://localhost:4000/api/error HTTP/1.1